name: Rust

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 2:00 UTC every day (to give the release process 2h to complete).
    - cron: '0 2 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Prepare pages
      run: ./prepare-pages.sh
    - name: Deploy GitHub Pages
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        git worktree add gh-pages gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../output/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force
